---

- name: Install EPEL (Extra Packages for Enterprise Linux) Release
  yum:
    name: epel-release
    state: latest
    update_cache: yes

- name: Install NGINX
  yum:
    name: nginx
    state: latest
    update_cache: yes

# - name: Configure NGINX CFG
#   replace:
#     path: /etc/nginx/nginx.conf
#     regexp: '/usr/share/nginx/html;'
#     replace: '/var/www;'
#     backup: yes

- name: Index to server
  copy:
    src: index.html
    dest: /usr/share/nginx/html/index.html
    owner: root
    group: root
    mode: 0644

- name: Enable NGINX on boot
  command: systemctl enable nginx

- name: Start NGINX
  command: systemctl start nginx
